### ISSUE TITLE
Phoneset is wrong! There are 115 phonemes!

### ISSUE THREAD

**Issue by bond005** [nsu-ai/russian_g2p#17]
```
>>> from russian_g2p import Grapheme2Phoneme
>>> your_transcriptor = Grapheme2Phoneme()
>>> len(your_transcriptor.russian_phonemes)
115
```
But why? What are these 115 phonemes?

**Comment by nsu-ai** [comment]
Fixed in [ad0832b](https://github.com/nsu-ai/russian_g2p/commit/ad0832b8eff3d933448e6de0727deba71ac8d10c), implemented a switch for enabling/disabling long phonemes in transcriptions
